apiVersion: rbac.authorization.k8s.io/v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: stakater-workload-monitoring-prometheus
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: stakater-workload-monitoring-prometheus
  subjects:
  - kind: ServiceAccount
    name: stakater-workload-monitoring-prometheus
    namespace: stakater-workload-monitoring
kind: RoleBindingList
