apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-echo-hello-world
  namespace: tekton-pipelines
spec:
  steps:
    - name: build-simple
      image: docker.io/library/busybox
      command:
        - /bin/sh
      args:
        - -c
        - "echo hello world"