apiVersion: v1
kind: Secret
metadata:
  name: stakater-git-auth
  namespace: tekton-pipelines
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <password>