apiVersion: v1
kind: Secret
metadata:
  name: stakater-registry-auth
  namespace: tekton-pipelines
  annotations:
    tekton.dev/docker-0: https://index.docker.io
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <password>