apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-postgresql-config
  labels:
    app: postgres
    category: service
data:
  POSTGRES_DB: inventory
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password