---
# Source: application/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: review
    group: com.stakater.platform
    provider: stakater
    version: "1.0.0"
    chart: "application-0.0.12"
    release: "NAMESPACE_NAME-review"
    heritage: "Tiller"
  name: review
---
# Source: application/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  labels:
    app: review
    group: com.stakater.platform
    provider: stakater
    version: "1.0.0"
    chart: "application-0.0.12"
    release: "NAMESPACE_NAME-review"
    heritage: "Tiller"
  name: review
spec:
  selector:
    app: review
    
  ports:
    - name: https
      port: 8080
      targetPort: 8080
    
---
# Source: application/templates/deployment.yaml

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: review
    group: com.stakater.platform
    provider: stakater
    version: "1.0.0"
    chart: "application-0.0.12"
    release: "NAMESPACE_NAME-review"
    heritage: "Tiller"
  name: review
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: review
        group: com.stakater.platform
        provider: stakater
        version: "1.0.0"
        chart: "application-0.0.12"
        release: "NAMESPACE_NAME-review"
        heritage: "Tiller"
        app: review
        category: backend
        
    spec:
      containers:
      - name: review
        image: "stakater/stakater-nordmart-review:v0.0.2"
        imagePullPolicy: IfNotPresent
        env:
          - name: DB_NAME
            value: nordmartDB
          - name: MONGO_HOST
            value: mongodb-svc
          - name: JAEGER_ENDPOINT
            value: http://jaeger-collector.istio-system:14268/api/traces
          
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        
      serviceAccountName: review        
---
# Source: application/templates/clusterrole.yaml

---
# Source: application/templates/clusterrolebinding.yaml

---
# Source: application/templates/configmap.yaml

---
# Source: application/templates/ingress.yaml

---
# Source: application/templates/pvc.yaml

---
# Source: application/templates/role-binding.yaml

---
# Source: application/templates/role.yaml

---
# Source: application/templates/routes.yaml

---
# Source: application/templates/secret.yaml

